### ISSUE TITLE
Cannor use import statement outside a module

### ISSUE THREAD

**Issue by Enkdress** [weblineindia/ReactJS-QRCode-Scanner#1]
Hi, 
 
I am having this error in NextJS and I don't know why

```
/home/enkdress/Documents/work/control-covid/control/node_modules/react-weblineindia-qrcode-scanner/lib/index.js:36
import React, { Component } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack-internal:///react-weblineindia-qrcode-scanner:1:18)
    at Object.react-weblineindia-qrcode-scanner (/home/enkdress/Documents/work/control-covid/control/.next/server/static/development/pages/scanQr.js:171:1)
    at __webpack_require__ (/home/enkdress/Documents/work/control-covid/control/.next/server/static/development/pages/scanQr.js:23:31)
    at eval (webpack-internal:///./pages/scanQr.js:8:91)
    at Module../pages/scanQr.js (/home/enkdress/Documents/work/control-covid/control/.next/server/static/development/pages/scanQr.js:115:1)
    at __webpack_require__ (/home/enkdress/Documents/work/control-covid/control/.next/server/static/development/pages/scanQr.js:23:31)
    at Object.5 (/home/enkdress/Documents/work/control-covid/control/.next/server/static/development/pages/scanQr.js:126:18)
    at __webpack_require__ (/home/enkdress/Documents/work/control-covid/control/.next/server/static/development/pages/scanQr.js:23:31)
    at /home/enkdress/Documents/work/control-covid/control/.next/server/static/development/pages/scanQr.js:91:18
```

**Comment by Enkdress** [comment]
here is the code that Im doing

``` javascript
import QrReader from 'react-weblineindia-qrcode-scanner';

const ScanQR = () => {
  const scan = (data) => {
    console.log(data);
  };

  return <QrReader legacyMode onScan={scan} />;
};

export default ScanQR;
```

**Comment by partners-wli** [comment]
Hello @Enkdress ,

Thank you for using our component. Upon further investigating the issue posted by you, here is the workaround.

For Next.js , use dynamic import instead of usual import.

```

import dynamic from 'next/dynamic'
const QrReader = dynamic(() => import('react-weblineindia-qrcode-scanner').then((a) => a.QrReader), {ssr: false});
```

Feel free to message us if you still find any error.

Thnx.
